In [1]:
import numpy as np

In [2]:
A = np.array([[1, 2], [3, 0]])

In [3]:
print (A.shape)
print (A[:,0])  #first column
print (A[1,:])  #sefirst column

(2, 2)
[1 3]
[3 0]


In [4]:
A1 = np.array([[1, 2],
               [5, 0]])

B1 = np.array([[0, 1],
               [-1, 2]])

print (A1 + B1)

print (np.dot(A1, B1))

[[1 3]
 [4 2]]
[[-2  5]
 [ 0  5]]


In [5]:
A1

array([[1, 2],
       [5, 0]])

In [6]:
print (A1.T)

[[1 5]
 [2 0]]


In [7]:
invA1 = np.linalg.inv(A1)

In [8]:
print (np.dot(A1, invA1))

[[1. 0.]
 [0. 1.]]


In [11]:
a = np.array([[2, 3], [-1, 4]])

In [13]:
print(np.linalg.det(a))

11.000000000000002


### System of Linear Equations

In [15]:
A = np.array([[1, 5, -1],
              [2, 3, -2],
              [-3, 4, 0]
             ])

b = np.array([1, 2, 0])

invA = np.linalg.inv(A)

x = np.dot(invA, b)

print(x)

[ 0.  0. -1.]


In [17]:
#verify

print (np.dot(A, x)) Í

[1. 2. 0.]
